### ISSUE TITLE
Laggy Scrolling with Vimium in Firefox when Fractional Scaling is Enabled in wayland

### ISSUE THREAD

**Issue by niekdomi** [gdh1995/vim-plus#1176]
**Description:**
I am experiencing laggy scrolling in Firefox (+ wayland) when using Vimium with fractional scaling enabled. This issue occurs specifically when scrolling with the `j` or `k` keys.

**Additional Details:**
- Operating System: Fedora 40 + Gnome 46.3 (wayland)
- Firefox Version: (128)
- Display Configuration: Fractional scaling enabled

**Notes:**
I am unsure if this issue is caused by Firefox or Vimium

**Comment by gdh1995** [comment]
How "laggy" did your Firefox scrolls on `j`? Did the speed change bigger and smaller frequently and by turn? Will it work as expected if you disable "fractional scaling" ?

If Vimium C works well when no fractional scaling, then I wonder: what about a single `d` (scrollPageDown) or even `G` (scrollToBottom) - will it scroll smoothly or still laggy?

The word "single" means during tests you should press down a key and release it as soon as possible.

**Comment by gdh1995** [comment]
Hello, just now I tested a fresh Fedora 40 (ISO live), and reproduced the jitter. Things are worse on my PC.

- Hardware and system
  - Intel 13900K (5.2 GHz limited) + NV GTX 4090 (although the ISO live system may has a poor GPU driver)
  - a monitor of 4K + 144Hz, and running at 4K + 60Hz
  - Fedora-Workstation-Live-x86_64-40-1.14.iso, installed onto a U disk of 128GB
  - Gnome + Wayland
  - use `dnf` to update `gnome-*` and `firefox`
- Test targets
  - Firefox: both the default `version in ISO` (maybe 124?) and the updated `v128`
  - Vimium C: both `1.99.999` and `2.11.2-mv2` (compiled from source code)
  - Gnome: `46.0` and `46.3`
  - Screen scale: `200%` and `175%`
- Some smooth scrolling
  - `j` and `k` works as expected on the Vimium C Options page and MS Bing search result pages
- Some broken scrolling
  - on the startup page (https://fedoraproject.org/start) `j` hangs frequently
    - it scrolls step by step during a few frames, stops for a big while and then scrolls by a much bigger step
    - sometimes the step for a big stop can be as small as a normal smooth-scrolling step, although I don't know why
  - during my tests, no trick would make `j` (scrollDown) smooth

Therefore, I used Firefox's DevTools to capture performance data, and got the below 2 figures:
- the memory consumption of the parent process is not so stable during scrolling
  - everytime the memory increases, rendering stops for a while
  - when the memory decreases, rendering continues and then takes a bit longer while
  - when the new rendering operation finishes I see the page scrolls by a longer distance

![Screenshot 2024-07-30 at 14-16-22 Firefox 128 – Linux – 7_30_2024 6 11 39 PM UTC – Firefox Profiler](https://github.com/user-attachments/assets/f249548b-d685-4c57-be69-f76c22107755)
- [Firefox 2024-07-30 14.11 profile.json.gz](https://github.com/user-attachments/files/16432191/Firefox.2024-07-30.14.11.profile.json.gz)

A much verbose profiling got the below figure:
- so I have no idea how to "fix" this jitter on Vimium C side
- if you use https://bugzilla.mozilla.org/, then you may search in it for others' solutions, or file a new bug

![Screenshot 2024-07-30 at 14-23-29 Firefox 128 – Linux – 7_30_2024 6 20 32 PM UTC – Firefox Profiler](https://github.com/user-attachments/assets/845804f3-0825-4d8b-bf6f-bea9b5a8760a)
