### ISSUE TITLE
why does `vimium://status/toggle` make exclusion rules not work

### ISSUE THREAD

**Issue by OnceThenEver** [gdh1995/vim-plus#455]
For example, one of my rules is:
`:https://www.bilibili.com`         `- 0 <space> =`
and one mapping is:
`map <space> scrollDown`
Then, space will conduct `scrollDown`, ignoring the rule, rather than Play / Pause, the default action.

**Comment by gdh1995** [comment]
It's because `toggle` means to toggle between `enabled` and `given passKeys`, and in your case `toggle-disabled` should work - see https://github.com/gdh1995/vimium-c/wiki/Enable-or-Disable-all-frames-by-a-shortcut#how-to-switch-between-two-statuses.

**Comment by gdh1995** [comment]
Well I think, "full-enabled" is just "being always enabled - no pass keys are bound to this tab"; there're two sources of pass keys: one is from the exclusion table, and the other from `vimium://status/***` has a higher priority.

So, it's not so clear for me "whether pass keys take effects or not" - which pass keys are you saying? while "fully-enabled", "partly enabled" and "fully-disabled" are just very accurate.

While "full-disabled" is a special case - when entered by `vimium://status`, it may have a small list of hooked keys to switch statuses, and then those key mappings still work in this forced mode.

BTW, I'll update the English translation of "full enabled/disabled" to "fully ..." in a next version.

**Comment by OnceThenEver** [comment]
My mistake, only `vimium://` commands are to my question, the title was wrong.

**Comment by OnceThenEver** [comment]
`vimium://` commands have effects on two parts: rules and keys, and both of them have two states: on/off. So the combinations are:
- key on; rule on
- key off; rule on
- key on; rule off
- key off; rule off (but it's unlikely useful, so doesn't count)
Switching between the three choices above is mathematically reliant and clear.

As for
> While "full-disabled" is a special case - when entered by vimium://status, it may have a small list of hooked keys to switch
> statuses, and then those key mappings still work in this forced mode.
hooked keys list can be safely ignored as HUD need only to present general information.

> especially because your words look too long to read quickly.
I may truncate further:
- key on; rule off
- key off; rule on
- key on; rule on
or you may render the on part as green and the off part red.

**Comment by OnceThenEver** [comment]
Forgive my inability to read the source code, I can only advise from a pure user's perspective.

**Comment by gdh1995** [comment]
The English version of such tips are very similar to those in philc/Vimium (https://github.com/philc/vimium/blob/master/pages/options.html#L39). Now I think I may update the Chinese version:
```
Vimium 快捷键 全部生效
Vimium 快捷键 部分停用
Vimium 快捷键 完全停用
```

**Comment by gdh1995** [comment]
https://github.com/gdh1995/vimium-c/wiki/Enable-or-Disable-all-frames-by-a-shortcut#explain-3-statuses has been added.
