### ISSUE TITLE
moveTabToIncognito doesn't work anymore in Mac Firefox

### ISSUE THREAD

**Issue by ranelpadon** [gdh1995/vim-plus#461]
**Describe the bug**

I often use the `moveTabToIncognito` since it's quite handy for converting the current page/tab to Private/Incognito mode.
But seems to be not working anymore with latest Firefox version. 

**To Reproduce**
1. Put a mapping to `moveTabToIncognito` command:
   
    <img width="380" alt="Screen Shot 2021-10-19 at 8 56 14 PM" src="https://user-images.githubusercontent.com/4292088/137914782-7042ca12-6527-4154-907b-a27f9821bf40.png">

2. Go to a page/tab.
3. Try to execute the hotkey(s)
4. The page/tab will not be moved to Private/Incognito mode.

**Browser, OS and Vimium C versions**

- Browser name: Firefox
- Browser version: Version 93.0 (latest)
- Vimium C version:  Version 1.93.1 (latest)
- OS name and version: Mac OS (Mojave) 10.4.6 / Darwin Kernel Version 18.7.0

BTW, thanks for your work on this amazing plugin. :)

**Comment by ranelpadon** [comment]
@gdh1995 I got a new Mac M1 Pro recently, and copied my Vimium C configuration from my older Mac. Everything is fine, except the `moveTabToIncognito`: it fires the `removeTab` instead for some reason. I'm using the newer Mac with Firefox **105.0b5** and Vimium **1.99.3**. It's working fine though in my older Mac with Firefox **104.0.1** and Vimium **1.99.3**.

Likewise, I'm thinking if I should re-open this issue, or file a new one for Mac M1 Firefox? Thanks. :)

**Comment by gdh1995** [comment]
&nbsp;Have you tried mapping a new plain key (e.g. letter key) to this command？



---Original---
From: ***@***.***&gt;
Date: Fri, Sep 2, 2022 00:54 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] moveTabToIncognito doesn't work anymore in Mac Firefox (Issue #461)

**Comment by ranelpadon** [comment]
@gdh1995 I tried these mapping to check if there are collisions and all of them have the same behavior: closing tab instead of moving it to Incognito:
```vim
map gp moveTabToIncognito
map P moveTabToIncognito

map q moveTabToIncognito
map Q moveTabToIncognito

map z moveTabToIncognito
map Z moveTabToIncognito
```

My mappings are exactly the same to that of my older Mac (via export/import config). Kinda strange that it only happens in the M1 Mac. Could you please suggest further debugging steps to narrow down the issue? Thanks

**Comment by gdh1995** [comment]
Oh please ensure the `Allow` radio is selected:
![image](https://user-images.githubusercontent.com/5547703/188079656-1eae58ba-d233-4c40-ae7e-a79f6324bd6d.png)

In fact `moveTabToIncognito` includes 2 steps: open a current tab URL in incognito, and then close a current normal tab. When the `Allow` radio is not selected, Vimium C can not finish the first step.

**Comment by ranelpadon** [comment]
@gdh1995 You're right, this is the culprit! Allowing the plugin to run in Incognito fixes the issue. It happened because I used Firefox sync to copy my Firefox settings/plugins from my older Mac. I think the "syncing" doesn't automatically copy the plugins' Incognito settings and will just use the default settings. Hence, they need to be re-enabled.

Thanks a lot for your time and guidance. I'm a happy man again. :)
