### ISSUE TITLE
未设置按键"z" ,但是会导致其他插件按"z"失效

### ISSUE THREAD

**Issue by TangTank** [gdh1995/vim-plus#668]
**Describe the bug**
我并没有映射"z"这个按键，但是我在网页中使用视频速度控制插件时，按下"z"无法响应，禁用本插件或者如果使用"Surfingkeys"插件,没有该问题。

**Browser, OS and Vimium C versions**
- Browser name: EDGE
- Browser version: 102
- Vimium C version: 1.98.2
- OS name and version: Win10

**Comment by gdh1995** [comment]
默认快捷键里 zH, zL 会导致第一个 `z` 被屏蔽。

按第2次`z`的时候，因为找不到`zz`，会重新开始匹配，也就是把这次`z`视为zH, zL的前缀键，这样紧接着的 H/L 就能触发快捷键了。

想在第2次时模拟 `z` 的话，可以创建 `map zz dispatchEvent .....`，具体用法参考 https://github.com/gdh1995/vimium-c/wiki/Trigger-commands-in-an-input-box#on-esc-not-blur-but-trigger-a-pages-escape
