### ISSUE TITLE
Possible to refer to default search engine in custom search engines with a keyword?

### ISSUE THREAD

**Issue by archelaus** [gdh1995/vim-plus#972]
**Issue Description:**
Currently, when using custom search engines, there doesn't appear to be a straightforward way to refer to the default search engine using a keyword. This limitation hinders users who frequently switch between search engines and desire a convenient method to access their default search engine without having to remember or type its specific keyword or address.

**Expected Behavior:**
It would be highly beneficial if there was a solution to enable users to reference their default search engine within custom search engines using a designated keyword.

**Comment by gdh1995** [comment]
There's a special name for the default search engine - it's `~`. So you may type `~ foo` to search `foo` in a default engine.

You may also add your default search engine to the `Custom search engines` with some other names, like this:
![image](https://github.com/gdh1995/vimium-c/assets/5547703/54d0956a-8ce0-441c-a5c0-412a40427c8f)

**Comment by archelaus** [comment]
> There's a special name for the default search engine - it's `~`. So you may type `~ foo` to search `foo` in a default engine.
> 
> You may also add your default search engine to the `Custom search engines` with some other names, like this: ![image](https://user-images.githubusercontent.com/5547703/255394512-54d0956a-8ce0-441c-a5c0-412a40427c8f.png)

Hey there, I'm aware of tilde thing. I was actually referring to the ability to have a shortcut for our default search engine that could be used in the custom search engines. It's not really a feature request but I was wondering if there was something already built-in that I might have missed.

For instance, I use search operator `site:` quite often and some other similar operators. So essentially I have to update all of my search engine queries every time I switch search engines.

**Comment by gdh1995** [comment]
By default Vimium C has run as you expect:
1. given any text and a search engine name, convert the `text` with `the selected search engine`
2. if the converted text "doesn't look like a URL", then convert it again with `the default search engine`

So, you may write such a custom search engine:
```
s: site:\ $S In site query
```

and then, when Vomnibar receives `s foo`, Vimium C will get `"site: foo"` and then convert it to a normal URL using your default search engine.

![image](https://github.com/gdh1995/vimium-c/assets/5547703/85150a03-505e-4820-a266-db64e8538973)

![image](https://github.com/gdh1995/vimium-c/assets/5547703/edae6048-faaa-4d97-aaf1-e8376d9e07e5)
