### ISSUE TITLE
How to Activate Vomnibar Immediately After Creating New Tab

### ISSUE THREAD

**Issue by ryan6416** [gdh1995/vim-plus#979]
**Describe the bug**:
When using the command `map t createTab | Vomnibar.activate` or `map t createTab | Vomnibar.activateInNewTab` in Vimium C, the expected behavior is that a new tab is created and the Vomnibar is immediately activated in the new tab. However, the Vomnibar does not activate as expected. The command only opens a new tab without activating the Vomnibar.

**Steps to reproduce the behavior**:
1. Install the Vimium C extension in Chrome Beta.
2. Install the [Vimium C NewTab extension](https://github.com/gdh1995/vimium-c-helpers/tree/master/newtab).
3. Open the Vimium C options page by clicking on the Vimium C icon in the browser's toolbar and selecting "Options".
4. In the "Custom key mappings" section, add the following mapping: `map t createTab | Vomnibar.activate` or `map t createTab | Vomnibar.activateInNewTab`.
5. Click the "Save Changes" button at the bottom of the page.
6. Close the options page and press the "t" key to trigger the command.
7. Observe that a new tab is created, but the Vomnibar is not activated.

**Expected behavior**:
When the "t" key is pressed, a new tab should be created and the Vomnibar should be immediately activated in the new tab.

**Browser name**: Chrome Beta
**Browser version**: Version 116.0.5845.42 (Official Build) beta (arm64)
**Vimium C version**: Vimium C 1.99.99, Google Chrome 116, macOS.
**OS name and version**: macOS Ventura 13.4

Please let me know if there's any additional information I can provide to help debug this issue. Thank you for your time and assistance.

**Comment by gdh1995** [comment]
No `|` is not a supported syntax of key mappings in Vimium C.

You may try `map t createTab $then="Vomnibar.activate"` as said in https://github.com/gdh1995/vimium-c-helpers/issues/16#issuecomment-917598571 .

However, please notice that, Vomnibar can only show on a normal web page like `https://www.google.com`, but (usually) not on your browser's NewTab page like `chrome://newtab`.
